{
 "title": "k8s-node-list",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Node列表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node List Resource",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "machine_cpu_cores{}", "legendFormat": "__auto" },
    { "expr": "machine_memory_bytes{}", "legendFormat": "__auto" },
    {
     "expr": "container_memory_working_set_bytes{id=\"/\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (machine_memory_bytes{})) - (sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\"}))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\"} ))/ (sum by (kubernetes_io_hostname) (machine_memory_bytes{}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\"})) - (sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\"})) / (sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\"}))",
     "legendFormat": "__auto"
    },
    { "expr": "kubelet_running_pods", "legendFormat": "__auto" },
    {
     "expr": "kubelet_running_containers{container_state=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node List Status",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "kube_node_info{}", "legendFormat": "__auto" },
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{ condition=\"MemoryPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{ condition=\"PIDPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{ condition=\"DiskPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    { "expr": "kube_node_spec_unschedulable{}", "legendFormat": "__auto" },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"cpu\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node列表-资源动态(Nodes List)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage(Nodes List)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_io_hostname) (rate(container_cpu_usage_seconds_total{id=\"/\"}[30s]))",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "MEM Used Of Node(Node List)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Of Node(Node List)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bytes", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_io_hostname) (rate(container_network_receive_bytes_total{id=\"/\"}[1m]))",
     "legendFormat": "-> {{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (rate(container_network_transmit_bytes_total{id=\"/\"}[1m]))",
     "legendFormat": "<- {{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Node列表-资源动态(Pods Summary Of Nodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage(Pods Summary Of Node)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "percentunit", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",pod!=\"\"}[30s])) by (kubernetes_io_hostname)",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    },
    {
     "title": "MEM Used(Pod Summary Of Nodes )",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{container!=\"POD\",container!=\"\",pod!=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network( Pods Summary Of Node)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_io_hostname) (rate(container_network_receive_bytes_total{container=\"POD\",container!=\"\",pod!=\"\"}[1m]))",
       "legendFormat": "-> {{kubernetes_io_hostname}}"
      },
      {
       "expr": "sum by (kubernetes_io_hostname) (rate(container_network_transmit_bytes_total{container=\"POD\",container!=\"\",pod!=\"\"}[1m]))",
       "legendFormat": "<- {{kubernetes_io_hostname}}"
      }
     ]
    }
   ]
  }
 ]
}