{
 "title": "k8s-app-metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\", container!=\"POD\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Container简况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container List",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"$container\",resource=\"cpu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"$container\",resource=\"cpu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"$container\",resource=\"memory\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"$container\",resource=\"memory\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_status_running{namespace=\"$namespace\",container=\"$container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"$container\"}[2h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$namespace\", pod=~\"^$container-.*\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\", namespace=\"$namespace\", pod=~\"^$container-.*\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\", namespace=\"$namespace\", pod=~\"^$container-.*\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\", namespace=\"$namespace\", pod=~\"^$container-.*\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\", namespace=\"$namespace\", pod=~\"^$container-.*\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"$namespace\", container=\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"$namespace\", container=\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"$namespace\", container=\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"$namespace\", container=\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$container\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$container\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores Limits by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$container\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$container\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 2 Hours)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"$container\"}[2h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod List",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\",pod=~\"^$container-.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\",pod=~\"^$container-.*\", phase=\"Running\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\",pod=~\"^$container-.*\", phase=\"Failed\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 * kube_pod_created{namespace=\"$namespace\",pod=~\"^$container-.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 * kube_pod_start_time{namespace=\"$namespace\",pod=~\"^$container-.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_restart_policy{namespace=\"$namespace\",pod=~\"^$container-.*\", type=\"Always\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"$container\", pod=~\"^$container-.*\"}[2h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container资源(Summary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Containers Summary)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$container\"}[30s])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "MEM Usage (Containers Summary)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container=\"$container\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Network (Containers Summary)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "Bps", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_network_receive_bytes_total{namespace=\"$namespace\", container=\"POD\", pod=~\"^$container-.*\"}[1m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", container=\"POD\", pod=~\"^$container-.*\"}[1m]))",
       "legendFormat": "Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Container资源(Pods of App)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Pods)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$container\"}[30s])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MEM Usage (Pods)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container=\"$container\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network (Pods)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "Bps", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_network_receive_bytes_total{namespace=\"$namespace\", container=\"POD\", pod=~\"^$container-.*\"}[1m])) by (pod)",
       "legendFormat": "Received By {{pod}}"
      },
      {
       "expr": "sum (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", container=\"POD\", pod=~\"^$container-.*\"}[1m])) by (pod)",
       "legendFormat": "Transmit By {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container资源(Pod relative to requests)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Pod relative to request)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$container\"}[30s])) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$container\", resource=\"cpu\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MEM Usage (Pod relative to request)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * container_memory_usage_bytes{namespace=\"$namespace\", container=\"$container\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$container\", resource=\"memory\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container资源(Pod relative to limits)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Pod relative to limits)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$container\"}[30s])) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$container\", resource=\"cpu\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MEM Usage (Pod relative to request)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * container_memory_usage_bytes{namespace=\"$namespace\", container=\"$container\"}) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$container\", resource=\"memory\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}