{
 "title": "k8s-cluster",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Node List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes UP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum(up{job=\"kubernetes-nodes\"} == 1) / count(up{ job=\"kubernetes-nodes\" }) ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node List Status",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "kube_node_info{}", "legendFormat": "__auto" },
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{ condition=\"MemoryPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{ condition=\"PIDPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{ condition=\"DiskPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    { "expr": "1000 * kube_node_created{}", "legendFormat": "__auto" },
    { "expr": "kube_node_spec_unschedulable{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node List Resource",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "machine_cpu_cores{}", "legendFormat": "__auto" },
    { "expr": "machine_memory_bytes{}", "legendFormat": "__auto" },
    {
     "expr": "container_memory_working_set_bytes{id=\"/\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (machine_memory_bytes{})) - (sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\"}))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\"} ))/ (sum by (kubernetes_io_hostname) (machine_memory_bytes{}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\"})) - (sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\"})) / (sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Namespace List",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    { "expr": "1000 * kube_namespace_created", "legendFormat": "__auto" },
    {
     "expr": "kube_namespace_status_phase{phase=\"Active\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_namespace_status_phase{phase=\"Terminating\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Deployment List",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    { "expr": "1000 * kube_deployment_created", "legendFormat": "{{ deployment }}" },
    {
     "expr": "kube_deployment_status_replicas",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_deployment_status_replicas_available",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable",
     "legendFormat": "{{ deployment }}"
    },
    {
     "expr": "kube_deployment_status_condition{condition=\"Available\",status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_deployment_status_condition{condition=\"Progressing\",status=\"true\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "DaemonSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "DaemonSet List",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      { "expr": "1000 * kube_daemonset_created", "legendFormat": "{{ deployment }}" },
      {
       "expr": "kube_daemonset_status_desired_number_scheduled",
       "legendFormat": "{{ deployment }}"
      },
      {
       "expr": "kube_daemonset_status_number_available",
       "legendFormat": "{{ deployment }}"
      },
      {
       "expr": "kube_daemonset_status_number_unavailable",
       "legendFormat": "{{ deployment }}"
      },
      {
       "expr": "kube_daemonset_status_number_misscheduled",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service List",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
     "targets": [
      { "expr": "1000 * kube_service_created", "legendFormat": "{{ deployment }}" },
      { "expr": "kube_service_info", "legendFormat": "{{ deployment }}" },
      { "expr": "kube_service_spec_type", "legendFormat": "{{ deployment }}" }
     ]
    }
   ]
  },
  {
   "title": "Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Restarts(Last 15 Minutes)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by (pod) (delta(kube_pod_container_status_restarts_total[15m]) > 0))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Restarts(Last 2 Hours)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by (pod) (delta(kube_pod_container_status_restarts_total[2h]) > 0))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods Running Count",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kube_pod_status_phase{}) by (phase)",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Pods Restarted(Last 15 Minutes)",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by (pod)(delta(kube_pod_container_status_restarts_total[15m]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pods Restarted(Last 2 Hours)",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 10 },
     "targets": [
      {
       "expr": "sum by (pod)(delta(kube_pod_container_status_restarts_total[2h]) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 8 Memory Of Pods",
     "type": "graph",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(8,sum(container_memory_usage_bytes{image!=\"\"}) by (pod))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "MEM Usage (Pod relative to request)",
     "type": "graph",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "topk(16,sum(100 * container_memory_usage_bytes{pod!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{pod!=\"\", resource=\"memory\"}) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "TOP 8 CPU Of Pods",
     "type": "graph",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(8, sum(rate(container_cpu_usage_seconds_total{image!=\"\", name=~\"^k8s_.*\", container!=\"POD\", pod!=\"\"}[1m])) by (pod))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "CPU Usage (Pod relative to request)",
     "type": "graph",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "topk(8,sum(100 * irate(container_cpu_usage_seconds_total{pod!=\"\"}[30s])) by (pod) / sum(kube_pod_container_resource_requests{pod!=\"\", resource=\"cpu\"}) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}