{
 "title": "k8s-tops",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Nodes Top", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "PIDPressure Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{condition=\"PIDPressure\", status!=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MemoryPressure Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{condition=\"MemoryPressure\", status!=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DiskPressure Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{condition=\"DiskPressure\", status!=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Restarted(Last 2 Hours)",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 2 },
   "targets": [
    {
     "expr": "sum by (pod)(delta(kube_pod_container_status_restarts_total[2h]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 2 Hours)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{pod!=\"\"}[2h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods UnRunning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 CPU Of Nodes (CPUUsed)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "topk(3,sum by (kubernetes_io_hostname) (rate(container_cpu_usage_seconds_total{id=\"/\"}[30s])))",
     "legendFormat": "Usage: {{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Top 3 CPU Of Nodes (CpuUsed/CpuTotal)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "topk(3,sum by (kubernetes_io_hostname) (rate(container_cpu_usage_seconds_total{id=\"/\"}[30s])) / sum by (kubernetes_io_hostname) (machine_cpu_cores{}))",
     "legendFormat": "Percent: {{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Top 3 MEM Of Nodes(MEMUsed)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\"}))",
     "legendFormat": "Used: {{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Top 3 MEM Of Nodes(MemUsed/MemTotal)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\"})/sum by (kubernetes_io_hostname) (machine_memory_bytes{}))",
     "legendFormat": "Percent: {{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Pods Top",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 8 Memory Of Pods",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(8,sum(container_memory_usage_bytes{image!=\"\"}) by (pod))",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "TOP 8 CPU Of Pods",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(8, sum(rate(container_cpu_usage_seconds_total{image!=\"\", name=~\"^k8s_.*\", container!=\"POD\", pod!=\"\"}[1m])) by (pod))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "MEM Usage (Pod relative to request)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum(100 * container_memory_usage_bytes{pod!=\"\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{pod!=\"\", resource=\"memory\"}) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage (Pod relative to request)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "topk(8,sum(100 * irate(container_cpu_usage_seconds_total{pod!=\"\",container!=\"\"}[30s])) by (pod) / sum(kube_pod_container_resource_requests{pod!=\"\", resource=\"cpu\"}) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MEM Usage (Pod relative to limits)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum(100 * container_memory_usage_bytes{pod!=\"\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{pod!=\"\", resource=\"memory\"}) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage (Pod relative to limits)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "topk(8,sum(100 * irate(container_cpu_usage_seconds_total{pod!=\"\",container!=\"\"}[30s])) by (pod) / sum(kube_pod_container_resource_limits{pod!=\"\", resource=\"cpu\"}) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}