{
 "title": "k8s-kubelet",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "kubelet-node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Resource",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "machine_cpu_cores{kubernetes_io_hostname=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "machine_memory_bytes{kubernetes_io_hostname=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (machine_memory_bytes{kubernetes_io_hostname=\"$Node\"})) - (sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=\"$Node\"}))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=\"$Node\"} ))/ (sum by (kubernetes_io_hostname) (machine_memory_bytes{kubernetes_io_hostname=\"$Node\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"})) - (sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"})) / (sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{node=\"$Node\", condition=\"Ready\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{node=\"$Node\", condition=\"MemoryPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{node=\"$Node\", condition=\"PIDPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{node=\"$Node\", condition=\"DiskPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_spec_unschedulable{node=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\",node=\"$Node\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\",node=\"$Node\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\",node=\"$Node\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"cpu\",node=\"$Node\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 * kube_node_created{node=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "kubelet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Kubelet operation duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum (rate(kubelet_runtime_operations_duration_seconds_bucket{kubernetes_io_hostname=\"$Node\"}[2m])) by (operation_type,le))\n",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Kuebelet Operation Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (operation_type) (rate(kubelet_runtime_operations_total{kubernetes_io_hostname=\"$Node\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kuebelet Operation Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (operation_type) (rate(kubelet_runtime_operations_errors_total{kubernetes_io_hostname=\"$Node\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Start Duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum (rate(kubelet_pod_start_duration_seconds_bucket{kubernetes_io_hostname=\"$Node\"}[2m])) by (le))\n",
     "legendFormat": "pod99-histogram_quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(kubelet_pod_worker_duration_seconds_bucket{kubernetes_io_hostname=\"$Node\"}[2m])) by (le))\n",
     "legendFormat": "worker99-histogram_quantile"
    }
   ]
  },
  {
   "title": "Pod Start Rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kubelet_pod_start_duration_seconds_count{kubernetes_io_hostname=\"$Node\"}[5m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}} - Pod"
    },
    {
     "expr": "sum(rate(kubelet_pod_worker_duration_seconds_count{kubernetes_io_hostname=\"$Node\"}[5m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}} - Worker"
    }
   ]
  },
  {
   "title": "Storage Operation Duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum (rate(storage_operation_duration_seconds_bucket{kubernetes_io_hostname=\"$Node\"}[2m])) by (operation_name,volume_plugin, le))\n",
     "legendFormat": "{{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Storage Operation Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(storage_operation_duration_seconds_count{kubernetes_io_hostname=\"$Node\"}[5m])) by (operation_name, volume_plugin)",
     "legendFormat": "{{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Cgroup manager 99th quantile",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "s", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum (rate(kubelet_cgroup_manager_duration_seconds_bucket{kubernetes_io_hostname=\"$Node\"}[2m])) by (operation_type,le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cgroup manager operation rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kubelet_cgroup_manager_duration_seconds_count{kubernetes_io_hostname=\"$Node\"}[5m])) by (operation_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLEG relist duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum (rate(kubelet_pleg_relist_duration_seconds_bucket{kubernetes_io_hostname=\"$Node\"}[2m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLEG relist rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kubelet_pleg_relist_duration_seconds_count{kubernetes_io_hostname=\"$Node\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLEG relist interval 99th quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "s", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum (rate(kubelet_pleg_relist_interval_seconds_bucket{kubernetes_io_hostname=\"$Node\"}[2m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "s", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum (rate(rest_client_request_duration_seconds_bucket{kubernetes_io_hostname=\"$Node\"}[2m])) by (url,le))\n",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(rest_client_requests_total{kubernetes_io_hostname=\"$Node\", code=~\"2..\"}[5m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum (rate(rest_client_requests_total{kubernetes_io_hostname=\"$Node\", code=~\"3..\"}[5m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum (rate(rest_client_requests_total{kubernetes_io_hostname=\"$Node\", code=~\"4..\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum (rate(rest_client_requests_total{kubernetes_io_hostname=\"$Node\", code=~\"5..\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  }
 ]
}