{
 "title": "k8s-node",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(kube_pod_info{created_by_kind=\"DaemonSet\", created_by_name=\"node-exporter\",node=\"$Node\"}, pod_ip)"
    }
   },
   { "name": "InstancePort", "query": "9100" }
  ]
 },
 "panels": [
  { "title": "Node简况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Resource",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "machine_cpu_cores{kubernetes_io_hostname=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "machine_memory_bytes{kubernetes_io_hostname=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (machine_memory_bytes{kubernetes_io_hostname=\"$Node\"})) - (sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=\"$Node\"}))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=\"$Node\"} ))/ (sum by (kubernetes_io_hostname) (machine_memory_bytes{kubernetes_io_hostname=\"$Node\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"})) - (sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (container_fs_usage_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"})) / (sum by (kubernetes_io_hostname) (container_fs_limit_bytes{id=\"/\",device=~\"/dev/v.*\",kubernetes_io_hostname=\"$Node\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{node=\"$Node\", condition=\"Ready\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{node=\"$Node\", condition=\"MemoryPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{node=\"$Node\", condition=\"PIDPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_status_condition{node=\"$Node\", condition=\"DiskPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_node_spec_unschedulable{node=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\",node=\"$Node\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\",node=\"$Node\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\",node=\"$Node\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"cpu\",node=\"$Node\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_node_info{node=\"$Node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 * kube_node_created{node=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点内存信息",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "总内存(total)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\",kubernetes_io_hostname=~\"^$Node$\"})",
     "legendFormat": "使用量(used)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"}) - sum(container_memory_working_set_bytes{container!=\"\",kubernetes_io_hostname=~\"^$Node$\"})",
     "legendFormat": "空闲量(available)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "请求量(requests)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "限制量(limits)"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$Node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pods list",
   "type": "table",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$Node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node资源(Node Summary)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\", instance=\"$Instance:$InstancePort\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=\"$Instance:$InstancePort\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"node-exporter\", instance=\"$Instance:$InstancePort\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Of Node(Node Summary)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_io_hostname) (rate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=\"$Node\"}[30s]))",
     "legendFormat": "Usage: {{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (rate(container_cpu_system_seconds_total{id=\"/\",kubernetes_io_hostname=\"$Node\"}[30s]))",
     "legendFormat": "System: {{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (rate(container_cpu_user_seconds_total{id=\"/\",kubernetes_io_hostname=\"$Node\"}[30s]))",
     "legendFormat": "User: {{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "MEM Of Node(Node Summary)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=\"$Node\"})",
     "legendFormat": "Used: {{kubernetes_io_hostname}}"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname) (machine_memory_bytes{kubernetes_io_hostname=\"$Node\"})) - (sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=\"$Node\"}))",
     "legendFormat": "Avail: {{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Network Of Node(Node Summary)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_io_hostname) (rate(container_network_receive_bytes_total{id=\"/\", kubernetes_io_hostname=\"$Node\"}[1m]))",
     "legendFormat": "-> {{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum by (kubernetes_io_hostname) (rate(container_network_transmit_bytes_total{id=\"/\", kubernetes_io_hostname=\"$Node\"}[1m]))",
     "legendFormat": "<- {{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Node资源(Pods Summary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Of Node(Pods Summary)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percentunit", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",pod!=\"\",kubernetes_io_hostname=\"$Node\"}[30s])) by (kubernetes_io_hostname)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MEM Used Of Node(Pod Summary )",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_io_hostname) (container_memory_working_set_bytes{container!=\"POD\",container!=\"\",pod!=\"\",kubernetes_io_hostname=\"$Node\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Of Node( Pods Summary)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_io_hostname) (rate(container_network_receive_bytes_total{container=\"POD\",container!=\"\",pod!=\"\", kubernetes_io_hostname=\"$Node\"}[1m]))",
       "legendFormat": "-> {{kubernetes_io_hostname}}"
      },
      {
       "expr": "sum by (kubernetes_io_hostname) (rate(container_network_transmit_bytes_total{container=\"POD\",container!=\"\",pod!=\"\", kubernetes_io_hostname=\"$Node\"}[1m]))",
       "legendFormat": "<- {{kubernetes_io_hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node资源(Pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU (Pods)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "percentunit", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",pod!=\"\",kubernetes_io_hostname=\"$Node\"}[30s])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MEM Used Of Node(Pods )",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (container_memory_working_set_bytes{container!=\"POD\",container!=\"\",pod!=\"\",kubernetes_io_hostname=\"$Node\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Of Node( Pods)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_bytes_total{container=\"POD\",container!=\"\",pod!=\"\", kubernetes_io_hostname=\"$Node\"}[1m]))",
       "legendFormat": "-> {{pod}}"
      },
      {
       "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{container=\"POD\",container!=\"\",pod!=\"\", kubernetes_io_hostname=\"$Node\"}[1m]))",
       "legendFormat": "<- {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}