{
 "title": "k8s-deployments",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "deployment", "query": { "query": "label_values(deployment)" } }
  ]
 },
 "panels": [
  { "title": "Pods简况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container List",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_info{pod=~\"^$deployment-.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"^$deployment-.*\",resource=\"cpu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"^$deployment-.*\",resource=\"cpu\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"^$deployment-.*\",resource=\"memory\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"^$deployment-.*\",resource=\"memory\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_status_running{pod=~\"^$deployment-.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(kube_pod_container_status_restarts_total{pod=~\"^$deployment-.*\"}[2h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", pod=~\"^$deployment-.*\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\", pod=~\"^$deployment-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\", pod=~\"^$deployment-.*\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\", pod=~\"^$deployment-.*\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\", pod=~\"^$deployment-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"^$deployment-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{pod=~\"^$deployment-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{pod=~\"^$deployment-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{pod=~\"^$deployment-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"^$deployment-.*\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores Limits by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"^$deployment-.*\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"^$deployment-.*\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"^$deployment-.*\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 2 Hours)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{pod=~\"^$deployment-.*\"}[2h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod List",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "kube_pod_info{pod=~\"^$deployment-.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_status_phase{pod=~\"^$deployment-.*\", phase=\"Running\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_status_phase{pod=~\"^$deployment-.*\", phase=\"Failed\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 * kube_pod_created{pod=~\"^$deployment-.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 * kube_pod_start_time{pod=~\"^$deployment-.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_restart_policy{pod=~\"^$deployment-.*\", type=\"Always\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(kube_pod_container_status_restarts_total{pod=~\"^$deployment-.*\"}[2h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods资源(Summary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Containers Summary)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * irate(container_cpu_usage_seconds_total{pod=~\"^$deployment-.*\"}[30s]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MEM Usage (Containers Summary)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod=~\"^$deployment-.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network (Containers Summary)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "Bps", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_network_receive_bytes_total{pod=~\"^$deployment-.*\", container=\"POD\"}[1m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum (rate(container_network_transmit_bytes_total{pod=~\"^$deployment-.*\", container=\"POD\"}[1m]))",
       "legendFormat": "Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods资源(Pod Single)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Pods)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * irate(container_cpu_usage_seconds_total{pod=~\"^$deployment-.*\"}[30s])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MEM Usage (Pods)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod=~\"^$deployment-.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network (Pods)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_network_receive_bytes_total{pod=~\"^$deployment-.*\", container=\"POD\"}[1m])) by (pod)",
       "legendFormat": "Received By {{pod}}"
      },
      {
       "expr": "sum (rate(container_network_transmit_bytes_total{pod=~\"^$deployment-.*\", container=\"POD\"}[1m])) by (pod)",
       "legendFormat": "Transmit By {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods资源(Pod relative to requests)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Pod relative to request)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * irate(container_cpu_usage_seconds_total{pod=~\"^$deployment-.*\"}[30s])) by (pod) / sum(kube_pod_container_resource_requests{pod=~\"^$deployment-.*\", resource=\"cpu\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MEM Usage (Pod relative to request)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * container_memory_usage_bytes{pod=~\"^$deployment-.*\"}) by (pod) / sum(kube_pod_container_resource_requests{pod=~\"^$deployment-.*\", resource=\"memory\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods资源(Pod relative to limits)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Pod relative to limits)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * irate(container_cpu_usage_seconds_total{pod=~\"^$deployment-.*\"}[30s])) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"^$deployment-.*\", resource=\"cpu\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MEM Usage (Pod relative to request)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(100 * container_memory_usage_bytes{pod=~\"^$deployment-.*\"}) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"^$deployment-.*\", resource=\"memory\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}