#################################################################
# kubectl apply -f headless_service.yaml
# kubectl get -f headless_service.yaml -o wide
# kubectl get all -n headless-service -o wide
# kubectl delete -f headless_service.yaml
# 验证: 
#   kubectl exec -it check-pod1 -n headless-service -- /bin/bash
#   kubectl exec -it check-pod2 -n headless-service -- /bin/bash
#        nslookup headless-tomcat-service.headless-service.svc.cluster.local
#        nslookup headless-tomcat-service
#        curl http://headless-tomcat-service:8080 
#        nc -vz headless-tomcat-service 8080
#
#################################################################
# Headless Service（无头服务）是Kubernetes中的一种特殊类型的服务，不会为Pod分配Cluster IP，而是为每个Pod提供单独的DNS条目。
#   这使得可以直接通过Pod名称进行服务发现，而无需经过负载均衡或代理。
#   Headless Service适用于一些需要直接与每个Pod进行通信的场景，如数据库复制集群、分布式缓存等
#################################################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: headless-service
---
apiVersion: v1
kind: Service
metadata:
  name: headless-tomcat-service
  namespace: headless-service
spec:
  clusterIP: None
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: check-pod1
  namespace: headless-service
spec:
  containers:
    - name: check-pod1
      image: k8strials.harbor.com/library/ubuntu-net-base:01
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "while true; do sleep 3600; done"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  namespace: headless-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: k8strials.harbor.com/library/tomcat:9.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: check-pod2
  namespace: headless-service
spec:
  containers:
    - name: check-pod2
      image: k8strials.harbor.com/library/ubuntu-net-base:01
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "while true; do sleep 3600; done"]
---
