###############################
# Pod的重启策略: Never, 不论容器运行状态如何，kubelet都不会重启该容器
# 
# 实验:
#   kubectl apply -f pod-restart-never.yaml
#   kubectl get -f pod-restart-never.yaml
#     可以观察到pod/pod-restart-never-exit-failed 的Status是: Error, RESTARTS是0
#     可以观察到pod/pod-restart-never-exit-normal 的Status是: Completed, RESTARTS是0
#   kubectl get -n pod-restart-never-test pods pod-restart-never-exit-failed -o yaml
#     可以观察到pod/pod-restart-never-exit-failed
#   kubectl get -n pod-restart-never-test pods pod-restart-never-exit-failed -o jsonpath='{.status.phase}'
#     可以观察到pod/pod-restart-never-exit-failed的phase是: Failed
#   kubectl get -n pod-restart-never-test pods pod-restart-never-exit-failed -o jsonpath='{.status.containerStatuses}' |jq
#     可以观察到pod/pod-restart-never-exit-failed的容器命令是异常退出，未执行重启
#   kubectl get -n pod-restart-never-test pods pod-restart-never-exit-normal -o yaml
#     可以观察到pod/pod-restart-never-exit-normal
#   kubectl get -n pod-restart-never-test pods pod-restart-never-exit-normal -o jsonpath='{.status.phase}'
#     可以观察到pod/pod-restart-never-exit-normal的phase是: Succeeded
#   kubectl get -n pod-restart-never-test pods pod-restart-never-exit-normal -o jsonpath='{.status.containerStatuses}' |jq
#     可以观察到pod/pod-restart-never-exit-failed的容器命令是正常退出，未执行重启
###############################
---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-restart-never-test
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-restart-never-exit-failed
  namespace: pod-restart-never-test
  labels:
    app: pod-restart-never-exit-failed
spec:
  restartPolicy: Never
  containers:
  - name: pod-restart-never-exit-failed
    image: k8strials.harbor.com/library/busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "echo 'command:'$(date '+%Y-%m-%d %H:%M:%S') >> /data/record; sleep 60; exit 1;"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-restart-never-exit-normal
  namespace: pod-restart-never-test
  labels:
    app: pod-restart-never-exit-normal
spec:
  restartPolicy: Never
  containers:
  - name: pod-restart-never-exit-normal
    image: k8strials.harbor.com/library/busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "echo 'command:'$(date '+%Y-%m-%d %H:%M:%S') >> /data/record; sleep 60; exit 0;"]
---

