#  外部Service的用例
#  kubectl apply -f external_service_by_endpoints.yaml
#  kubectl get -f external_service_by_endpoints.yaml
#  kubectl describe -f external_service_by_endpoints.yaml
#  kubectl get all -n external-apps -o wide
#  kubectl exec -it busybox-pod -n external-apps -- sh
#     进入容器内后: 
#       使用 ping 命令来检查与外部数据库主机的网络连通性: ping -c3 192.168.57.254
#       使用 nc 命令来尝试建立 TCP 连接到外部数据库主机和端口: nc -vz 192.168.57.254 80
#       使用 nslookup: nslookup harbor 或者 nslookup harbor.external-apps.svc.cluster.local
#  kubectl delete -f external_service_by_endpoints.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-apps
---
kind: Endpoints
apiVersion: v1
metadata:
  # endpoint 的名称必须和服务的名称相匹配
  name: harbor
  namespace: external-apps
subsets:
  - addresses:
      # 外部服务 IP 地址 , 服务将连接重定向到 endpoint 的 IP 地址
      - ip: 192.168.57.254
    ports:
      # 外部服务端口 , endpoint 的目标端口
      - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: harbor
  namespace: external-apps
spec:
  ports:
    - port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: external-apps
spec:
  containers:
    - name: busybox
      image: k8strials.harbor.com/library/busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "while true; do sleep 3600; done"]
---
