###################################################
# kubectl apply    -f externalips_service.yaml
# kubectl get      -f externalips_service.yaml -o wide
# kubectl get all -n externalips-service -o wide
# kubectl describe -f externalips_service.yaml
# kubectl get pods -n externalips-service -o wide
# kubectl delete   -f externalips_service.yaml
# 验证: 
#     nc -vz $(kubectl get service/tomcat-service -n externalips-service -o jsonpath='{.spec.externalIPs[0]}') 30080
#     浏览器中访问: http://externalIPs:30080/
###################################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: externalips-service
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: externalips-service
spec:
  selector:
    app: tomcat
  externalIPs:
    - "192.168.57.201"
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: externalips-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: k8strials.harbor.com/library/tomcat:9.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
---
