########################################
#  Deployment Controller: 建立在 ReplicaSet 控制器之上，以受控速率更改实际状态， 使其变为期望状态
#
#  实验:
#    kubectl apply -f scheduler-controller-deployment.yaml 
#    kubectl get -f scheduler-controller-deployment.yaml -o wide
#    kubectl get -n scheduler-controller-deployment-test pods -o wide
#      可以观察到: 
#    kubectl delete -f scheduler-controller-deployment.yaml 
#      回收
########################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: scheduler-controller-deployment-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronted-deployment
  namespace: scheduler-controller-deployment-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: main-container
        image: k8strials.harbor.com/library/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "sleep 3600;"]
        resources:
          requests:
            memory: 32Mi
            cpu: 100m
          limits:
            memory: 32Mi
            cpu: 100m
---

