######################################################
# Taints 和 Tolerations: 用于控制 Pod 是否能够被调度到具有特定 Taint 的节点上
#
# 命令:
#   查看所有节点的taints情况
#     kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.taints}{"\n"}{end}'
#   给一个节点设置taint
#     kubectl taint nodes node-name special=true:NoSchedule
#   给一个节点删除taint
#     kubectl taint nodes node-name special=true:NoSchedule-
#
# 实验环境:
#   假定所有节点都被设置了taint: special=true:NoSchedule
#
# 实验:
#   kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'
#     输出所有节点
#   kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | xargs -I {} kubectl taint nodes {} special=true:NoSchedule
#     使用xargs, 每个节点都设置taint: special=true:NoSchedule
#   kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.taints}{"\n"}{end}'
#     查看每个节点的taints情况
#
#   kubectl apply -f scheduler-node-taints-tolerations.yaml 
#   kubectl get -f scheduler-node-taints-tolerations.yaml
#     观察到: pod/pod-with-tolerations 是Running
#     观察到: pod/pod-without-tolerations 是Pending
#   kubectl describe -f scheduler-node-taints-tolerations.yaml
#     观察pod-without-tolerations, 其他提示有: had untolerated taint {special: true}
#   
#   取消taints: 为了不影响以后的实验，记得取消taints
#     kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | xargs -I {} kubectl taint nodes {} special=true:NoSchedule-
#   再次查看pods情况，会发现: pod/pod-without-tolerations 是Running
#     kubectl get -f scheduler-node-taints-tolerations.yaml
#   查看taints, 确认已取消
#     kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.taints}{"\n"}{end}'
#   kubectl delete -f scheduler-node-taints-tolerations.yaml 
#     回收
######################################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: node-taints-tolerations-test
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-tolerations
  namespace: node-taints-tolerations-test
spec:
  restartPolicy: Never
  tolerations:
    - key: special
      operator: Equal
      value: "true"
      effect: NoSchedule
  containers:
    - name: container-with-tolerations
      image: k8strials.harbor.com/library/busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "sleep 3600;"]
      resources:
        requests:
          memory: 32Mi
          cpu: 100m
        limits:
          memory: 64Mi
          cpu: 200m
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-without-tolerations
  namespace: node-taints-tolerations-test
spec:
  restartPolicy: Never
  containers:
    - name: container-without-tolerations
      image: k8strials.harbor.com/library/busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "sleep 3600;"]
      resources:
        requests:
          memory: 32Mi
          cpu: 100m
        limits:
          memory: 64Mi
          cpu: 200m
---
