########################################
#  DaemonSet 确保全部（或者某些）节点上运行一个 Pod 的副本。 
#
#  实验:
#    kubectl apply -f scheduler-controller-daemonset.yaml 
#    kubectl get -f scheduler-controller-daemonset.yaml -o wide
#    kubectl get -n scheduler-controller-daemonset-test pods -o wide
#      可以观察到: 每个node上面都运行了backend pod
#    kubectl delete -f scheduler-controller-daemonset.yaml 
#      回收
########################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: scheduler-controller-daemonset-test
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: backend-daemonset
  namespace: scheduler-controller-daemonset-test
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: main-container
        image: k8strials.harbor.com/library/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "sleep 3600;"]
        resources:
          requests:
            memory: 32Mi
            cpu: 100m
          limits:
            memory: 32Mi
            cpu: 100m
---
