########################################
#  CronJob Controller: 允许以固定时间间隔或特定时间表运行作业
#
#  实验:
#    kubectl apply -f scheduler-controller-cronjob.yaml 
#    kubectl get -f scheduler-controller-cronjob.yaml -o wide
#    kubectl get all -n scheduler-controller-cronjob-test
#    kubectl delete -f scheduler-controller-cronjob.yaml 
#      回收
########################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: scheduler-controller-cronjob-test
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-test
  namespace: scheduler-controller-cronjob-test
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main-container
            image: k8strials.harbor.com/library/busybox:latest
            imagePullPolicy: IfNotPresent
            command: ["echo", "Hello, Kubernetes!"]
            resources:
              requests:
                memory: 32Mi
                cpu: 100m
              limits:
                memory: 32Mi
                cpu: 100m
---
