---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
stringData:
  username: YWRtaW4=
  password: YWRtaW4= 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion":1,
        "datasources":[
            {
                "access":"proxy",
                "editable":true,
                "name":"prometheus",
                "orgId":1,
                "type":"prometheus",
                "url":"http://prometheus.monitoring.svc.cluster.local:9090",
                "version":1
            }
        ]
    }
---
